# Deep Learning Lab - Exercise 1, Sept 24, 2021


### This is the draft notebook which has been shown during the exercise 1, containing some examples of things you should have tried yourself!

## 2.1 Those who are not familiar with Python

In [1]:
# Basic arithmetics
x = 5
y = x + 1
print(x)

5


In [2]:
# Printing with f-string

print(f"5 plus 1 is {y}")
print(f"this: {10 / 3} and this: {10 / 3 :.2f}")

5 plus 1 is 6
this: 3.3333333333333335 and this: 3.33


In [3]:
# type

z = 0.5
print(f"type of y is {type(y)}")
print(f"type of z is {type(z)}")

type of y is <class 'int'>
type of z is <class 'float'>


In [4]:
# list

my_list = [2, 4, 5]
print(my_list)

[2, 4, 5]


In [5]:
# index start at 0.
print(my_list[0])

2


In [6]:
# strings

hello = "hello"
sentence = "welcome to deep learning lab"
print(hello + ", " + sentence)

hello, welcome to deep learning lab


In [7]:
print(sentence[3:10])

come to


In [8]:
sentence.split()  # this is a list.

['welcome', 'to', 'deep', 'learning', 'lab']

In [9]:
L = sentence.split()
print(f"length of this list is: {len(L)}")

print(f"third word of the sentence is: {L[2]}")

length of this list is: 5
third word of the sentence is: deep


In [10]:
# Loops

# you can iterate over a list
for word in sentence.split():
  print(word)

print("----------")

welcome
to
deep
learning
lab
----------


In [11]:
# loop over index
for i in range(len(L)):

  print(i, L[i])

0 welcome
1 to
2 deep
3 learning
4 lab


In [12]:
# dictionary:

basket = {'apple': 4, 'banana': 2, 'orange': 5}

# iterate over key/value
for fruit, count in basket.items():
    print(fruit, count)

apple 4
banana 2
orange 5


In [13]:
# tuples

pair = (12, 14)
print(f"pair is {pair}")


pair is (12, 14)


In [14]:
# unpacking
a, b = pair
print(f"first element {a}")
print(f"second element {b}")

first element 12
second element 14


In [15]:
# booleans

a = True
b = False

print(a and b)

print("--------")

False
--------


In [16]:
if a:
  print('a is True')
  print(b)

a is True
False


# 2.2 Numpy

In [17]:
import numpy as np

In [18]:
# creating array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
# check shape
print(a.shape)

(2, 3)


In [20]:
print(a.dtype)

int64


In [21]:
# Python list
my_list = [1, 2, 3]

b = np.asarray(my_list, dtype=np.float32)
print(b)

[1. 2. 3.]


In [22]:
# random 
x = np.random.rand(4, 3)
x

array([[0.94799352, 0.62085102, 0.84129606],
       [0.14210153, 0.75817598, 0.76749312],
       [0.71680472, 0.02659154, 0.32163245],
       [0.43952601, 0.0173776 , 0.74961323]])

In [23]:
# built-in constructor
x2 = np.eye(4, 3)
x2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
# element-wise operations
print("addition -----------")
print(x + x2, '\n')

print("multiplication -----------")
print(x * x2, '\n')

print("mul with a scalar -----------")
print(2 * x, '\n')

print("division -----------")
print(x2 / x, '\n')

print("exponent -----------")
print((2 * x2) ** 2)

addition -----------
[[1.94799352 0.62085102 0.84129606]
 [0.14210153 1.75817598 0.76749312]
 [0.71680472 0.02659154 1.32163245]
 [0.43952601 0.0173776  0.74961323]] 

multiplication -----------
[[0.94799352 0.         0.        ]
 [0.         0.75817598 0.        ]
 [0.         0.         0.32163245]
 [0.         0.         0.        ]] 

mul with a scalar -----------
[[1.89598705 1.24170204 1.68259211]
 [0.28420306 1.51635196 1.53498625]
 [1.43360943 0.05318308 0.6432649 ]
 [0.87905203 0.03475519 1.49922647]] 

division -----------
[[1.05485953 0.         0.        ]
 [0.         1.318955   0.        ]
 [0.         0.         3.10913902]
 [0.         0.         0.        ]] 

exponent -----------
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]
 [0. 0. 0.]]


In [25]:
y = np.random.rand(3, 4)

In [26]:
x.shape

(4, 3)

In [27]:
y.shape

(3, 4)

In [28]:
# matrix multiplication
z = x @ y
z

array([[1.14982517, 1.18365404, 2.01055163, 1.23172265],
       [0.76661714, 0.99220925, 1.31415259, 0.6932877 ],
       [0.53885946, 0.41060064, 0.90906134, 0.60906507],
       [0.65036698, 0.53774828, 0.86844873, 0.45463272]])

In [29]:
z.shape

(4, 4)

In [30]:
z1 = np.matmul(x, y)
z1

array([[1.14982517, 1.18365404, 2.01055163, 1.23172265],
       [0.76661714, 0.99220925, 1.31415259, 0.6932877 ],
       [0.53885946, 0.41060064, 0.90906134, 0.60906507],
       [0.65036698, 0.53774828, 0.86844873, 0.45463272]])

In [31]:
z2 = x.dot(y)
z2

array([[1.14982517, 1.18365404, 2.01055163, 1.23172265],
       [0.76661714, 0.99220925, 1.31415259, 0.6932877 ],
       [0.53885946, 0.41060064, 0.90906134, 0.60906507],
       [0.65036698, 0.53774828, 0.86844873, 0.45463272]])

In [32]:
z

array([[1.14982517, 1.18365404, 2.01055163, 1.23172265],
       [0.76661714, 0.99220925, 1.31415259, 0.6932877 ],
       [0.53885946, 0.41060064, 0.90906134, 0.60906507],
       [0.65036698, 0.53774828, 0.86844873, 0.45463272]])

In [33]:
z.max(0)

array([1.14982517, 1.18365404, 2.01055163, 1.23172265])

In [34]:
z.max(1)

array([2.01055163, 1.31415259, 0.90906134, 0.86844873])

In [35]:
z.max()

2.0105516308440516

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
z_reshaped = z.reshape(2, 8)

In [38]:
z_reshaped.shape

(2, 8)

In [39]:
boo = np.array([True, False, True, True])
boo

array([ True, False,  True,  True])

In [40]:
~boo

array([False,  True, False, False])

In [41]:
q = np.array([1, 2, 3, 4])

In [42]:
q[boo]

array([1, 3, 4])

In [43]:
q[~boo]

array([2])

In [44]:
elements = [2, 3]

In [45]:
q[elements]

array([3, 4])

In [46]:
# apply a function to each element
np.log(q)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

# Simple applications

In [47]:
# Question: can I pass DLL if I skip the last assignment?
import numpy as np

# dot product

weights = np.array([0.15, 0.20, 0.25, 0.40])

my_score = (100, 100, 100, 0)
my_score_arr = np.asarray(my_score)

weights.dot(my_score_arr)

60.0

In [48]:
# functions

def pass_dll(my_grades):
    # grades: tuple or list.
    grades = np.asarray(my_grades)
    weights = np.array([0.15, 0.20, 0.25, 0.40])
    if grades.dot(weights) >= 60:
      return True
    else:
      return False 

scores = (100, 100, 100, 0)
print(f"I can pass with score: {scores} ? {pass_dll(scores)}")

scores = (50, 50, 70, 60)
print(f"I can pass with score: {scores} ? {pass_dll(scores)}")


I can pass with score: (100, 100, 100, 0) ? True
I can pass with score: (50, 50, 70, 60) ? False


In [49]:
# python class

class Exercise:

    # constructor
    def __init__(self, number, topic):
        # number: int
        # topic: string
        self.number = number
        self.topic = topic

    # method
    def get_topic(self):
        print(self.topic)

    def get_number(self):
        print(self.number)

ex01 = Exercise(1, "Introduction, compute resource.")
ex01.get_topic()
ex01.get_number()

ex02 = Exercise(2, "PyTorch basics.")
ex02.get_topic()

Introduction, compute resource.
1
PyTorch basics.
